theme                   = "catppuccin_macchiato"

[editor]
true-color              = true
auto-format             = true
color-modes             = true
scrolloff               = 50
mouse                   = false
indent-guides.render    = true
indent-guides.character = "▏"
soft-wrap.enable        = true
cursorcolumn            = true
rulers                  = [80, 120]
jump-label-alphabet     = "jfkdlsaurieowpqnvmcxz"

[keys.normal]
H                       = ":buffer-previous"
L                       = ":buffer-next"
"tab"                   = "expand_selection"
"S-tab"                 = "shrink_selection"
C-j                     = "page_down"
C-k                     = "page_up"
x                       = "extend_line_below"
X                       = "extend_line_above"


# [keys.normal]
# "ret"                 = "goto_word"

# [keys.normal.space]
# f                     = "file_picker_in_current_directory"
# F                     = "file_picker"
