# 2. Define Tinymist (Merged Block)
[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
exportPdf = "onSave"
preview.background.enabled = true
# Ensure these args are passed correctly to the binary
preview.background.args = ["--data-plane-host=127.0.0.1:6973", "--invert-colors=never"]

# 3. Define Clangd
[language-server.clangd]
command = "clangd"

# --- Language Configurations ---

[[language]]
name = "verilog"
indent = { tab-width = 2, unit = "  " }
scope = "source.verilog"
file-types = ["v", "vh", "vg", "sv", "svh"]
language-servers = ["verible"]
formatter = { command = "verible-verilog-format", args = ["--indentation_spaces=2", "-"] }
auto-format = true

[language-server.verible]
command = "verible-verilog-ls"

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["-"] }
language-servers = [ "clangd" ]

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typst"
file-types = ["typ"]
roots = ["typst.toml", ".git"]
auto-format = true
language-servers = [ "tinymist"]
auto-pairs = { '(' = ')', '{' = '}', '[' = ']', '"' = '"', '$' = '$' }

[[language]]
name = "python"
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
